development:
  adapter: mysql2
  database: hype_development
  username: root
  password: karmaK00l2112
  host: localhost
  encoding: utf8

test: 
  adapter: mysql2
  database: hype_test
  username: root
  password:
  host: localhost
  encoding: utf8

staging: 
  adapter: mysql2
  database: hype_staging
  username: root
  password: X861D84svTabosy
  host: localhost
  encoding: utf8

production: 
  adapter: mysql2
  database: hype_production
  username: root
  password: X861D84svTabosy
  host: localhost
  encoding: utf8
