defaults: &defaults
  groupon_key: 41550c408db4945fedee9121f4d982fd475ee594
  meetup_key: 5c567f13323a4b4864774622f1fb
  eventbrite_key: ZjRmMTc2NDlkMTRh
  songkick_key: 24q9kQ8Zmlqspxrl
  active_key: cy72tu6xtta533bmqw875ppm

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
