defaults: &defaults
  groupon_key: 010669153f12af0392daf44092bc22fa51ad8fb1
  meetup_key: 4c39747053606885579c1f1eb653d
  eventbrite_key: WPQSGYFXPAZ55ZIC7P
  songkick_key: 24q9kQ8Zmlqspxrl
  active_key: bjaq76juznexhx6rrtyzx9yk

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
